# Makefile generated automatically
all: PEQuestion1.class Dissector.class 
PEQuestion1.class:  PEQuestion1.java 
	/usr/bin/javac PEQuestion1.java
Dissector.class: Dissector.java
	/usr/bin/javac Dissector.java
