# Makefile generated automatically
all: TestShape.class Circle.class Equilateral.class Isoceles.class Rectangle.class Shape.class Triangle.class 
TestShape.class:  TestShape.java 
	/usr/bin/javac TestShape.java
Circle.class: Circle.java
	/usr/bin/javac Circle.java
Equilateral.class: Equilateral.java
	/usr/bin/javac Equilateral.java
Isoceles.class: Isoceles.java
	/usr/bin/javac Isoceles.java
Rectangle.class: Rectangle.java
	/usr/bin/javac Rectangle.java
Shape.class: Shape.java
	/usr/bin/javac Shape.java
Triangle.class: Triangle.java
	/usr/bin/javac Triangle.java
