# Makefile generated automatically
all: TestVehicle.class BigMotor.class Car.class MediumMotor.class Motorcycle.class SmallMotor.class Truck.class Vehicle.class 
TestVehicle.class:  TestVehicle.java 
	/usr/bin/javac TestVehicle.java
BigMotor.class: BigMotor.java
	/usr/bin/javac BigMotor.java
Car.class: Car.java
	/usr/bin/javac Car.java
MediumMotor.class: MediumMotor.java
	/usr/bin/javac MediumMotor.java
Motorcycle.class: Motorcycle.java
	/usr/bin/javac Motorcycle.java
SmallMotor.class: SmallMotor.java
	/usr/bin/javac SmallMotor.java
Truck.class: Truck.java
	/usr/bin/javac Truck.java
Vehicle.class: Vehicle.java
	/usr/bin/javac Vehicle.java
