# Makefile generated automatically
all: Memory.class MemoryBlock.class MemoryManager.class 
Memory.class:  Memory.java 
	/usr/bin/javac Memory.java
MemoryBlock.class: MemoryBlock.java
	/usr/bin/javac MemoryBlock.java
MemoryManager.class: MemoryManager.java
	/usr/bin/javac MemoryManager.java
