# Makefile generated automatically
all: GraphicsDriver.class Windows.class 
GraphicsDriver.class:  GraphicsDriver.java 
	/usr/bin/javac GraphicsDriver.java
Windows.class: Windows.java
	/usr/bin/javac Windows.java
