# Makefile generated automatically
all: hierarchy.class obj.class display.class 
hierarchy.class:  hierarchy.java 
	/usr/bin/javac hierarchy.java
obj.class: obj.java
	/usr/bin/javac obj.java
display.class: display.java
	/usr/bin/javac display.java
