# Makefile generated automatically
all: CutNPaste.class CharNode.class Buffer.class 
CutNPaste.class:  CutNPaste.java 
	/usr/bin/javac CutNPaste.java
CharNode.class: CharNode.java
	/usr/bin/javac CharNode.java
Buffer.class: Buffer.java
	/usr/bin/javac Buffer.java
