# Makefile generated automatically
all: PEQuestion2.class Node.class Tree.class 
PEQuestion2.class:  PEQuestion2.java 
	/usr/bin/javac PEQuestion2.java
Node.class: Node.java
	/usr/bin/javac Node.java
Tree.class: Tree.java
	/usr/bin/javac Tree.java
